### ISSUE TITLE
Instructor Feedback - Project Checkpoint 2

### ISSUE THREAD

**Issue by pawaitemadisoncollege** [kbishell/StPaulOnlineEnrollment#4]
- [x] There are some broken links on your readme.md. 
- [x] Nice job with the ERD. One table I think may be missing: roles. A user has one to many roles.
- [x] ERD question: Are all users staff? I'm asking because there is a staff id on the user table? Maybe instead there should be a userid on the staff table? 
- [x] ERD question: Contact. A contact could be a user, but they do not have to be,  is that right?
- [x] ERD question: If a student could have many registrations, how do you determine which one is current? Is a timestamp needed at all?
- [x] Nice job with your time log. Are you remembering to update your project plan (check off what's completed)?
- [x] Looks like you've gotten the hang of writing daos. Time to refactor and use a single dao (the generic dao). You will still keep unit tests to verify hibernate works with every entity, but you'll be able to slim down that persistence package to a single dao.
- [x]  implement .equals() on each entity so that you can thoroughly unit test, meaning you won't have to compare each instance variable individually like this: https://github.com/kbishell/StPaulOnlineEnrollment/blob/82dc54c43c458bbaaff4c0b7f0d00b65a2c26f4f/src/test/java/stpaul/lutheran/persistence/StaffDaoTest.java#L53
- [x] Remember to replace any system.out.printlns and stack trace statement with log4j. Example: https://github.com/kbishell/StPaulOnlineEnrollment/blob/eec64616172de3991d838d62550f800689e7c25a/src/test/java/stpaul/lutheran/test/util/Database.java#L43-L49

**Comment by kbishell** [comment]
Everything should be completed now except for the one Dao class I will try and do a little more research on this and start implementing. Thanks for your help.
